- hosts: all
  become: yes
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f /home/ansadmin/opt/Deployment.yml     
     - name: create new deployment
       command: kubectl apply -f /home/ansadmin/opt/Deployment.yml
