- hosts: all
  become: yes
  tasks:
    - name: Copy CA files
      copy:
        src: '{{item}}'
        dest: '/home/ansadmin/opt'
      loop:
        - Deployment.yml
        - Service.yml
       
