- hosts: all
  become: yes
  tasks: 
    -  name: a simple test
       copy:
         src: /home/ansadmin/opt/Deployment.yml
         dest: /home/ansadmin/opt
    -  name: a simple test
       copy:
         src: /home/ansadmin/opt/service.yml
         dest: /home/ansadmin/opt
