kind: Deployment
apiVersion: apps/v1
metadata:
   name: prodevops
spec:
   replicas: 1
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: prodevops
   template:
      metadata:
        labels:
          app: prodevops
      spec:
       containers:
        - name: c1
          image: suribau/maven1:v1.latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
