kind: Service                             
apiVersion: v1
metadata:
  name: prodevops
  labels:
    app: prodevops
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: prodevops                    
  type: LoadBalancer
