kind: Service                             
apiVersion: v1
metadata:
  name: prodevops
  labels:
    app: prodevops
spec:
  ports:
    - port: 8080                             
      targetPort: 8080                    
  selector:
    app: prodevops                    
  type: NodePort
